export const metadata = {
    title: 'Mahafuj Dashboard',
    description: 'Generated by create next app',
  }
const DashboardLayout = ({children}) => {
    return (
        <div>
            {children}
        </div>
    );
};

export default DashboardLayout;